CREATE DATABASE `crm_database` /*!40100 DEFAULT CHARACTER SET utf8 */;
use crm_database;

CREATE TABLE `tb_cliente` (
  `ID_CLIENTE` bigint(20) NOT NULL AUTO_INCREMENT,
  `CIDADE` varchar(255) DEFAULT NULL,
  `CPF_CNPJ` varchar(255) DEFAULT NULL,
  `DT_CADASTRO` datetime DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `ESTADO` varchar(255) DEFAULT NULL,
  `LIMITE_CREDITO` double DEFAULT NULL,
  `LOGRADOURO` varchar(255) DEFAULT NULL,
  `NM_CLIENTE` varchar(255) DEFAULT NULL,
  `NR_ENDERECO` int(11) DEFAULT NULL,
  `PORTE` int(11) DEFAULT NULL,
  `TELEFONE` varchar(255) DEFAULT NULL,
  `TP_CLIENTE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

CREATE TABLE `tb_contato` (
  `ID_CONTATO` bigint(20) NOT NULL AUTO_INCREMENT,
  `CARGO` int(11) DEFAULT NULL,
  `DEPARTAMENTO` int(11) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `NM_CONTATO` varchar(255) DEFAULT NULL,
  `TELEFONE` varchar(255) DEFAULT NULL,
  `ID_CLIENTE` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID_CONTATO`),
  KEY `FK_g90uxghxb13x9wqrdj6cb4krk` (`ID_CLIENTE`),
  CONSTRAINT `FK_g90uxghxb13x9wqrdj6cb4krk` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `tb_cliente` (`ID_CLIENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

